name: "Test"
on:
  [ push ]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "[SETUP] Checkout"
        uses: actions/checkout@v3
        with:
          depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: "[SETUP] Cargo toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: "[TEST] Run test"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: "[WRAPUP] Gather coverage"
        id: coverage  
        uses: actions-rs/grcov@v0.1
      - name: "[WRAPUP] Upload coverage"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          files: ${{ steps.coverage.outputs.report }}
